version: "3.4"

services:
    nginx:
        image: nginx:alpine
        restart: on-failure
        env_file:
            - .env
            - .env.local
        ports:
            - "${NGINX_PUBLIC_PORT:-8000}:80"
        depends_on:
            - php-fpm
        volumes:
            - ./docker/nginx/templates:/etc/nginx/templates:ro
            - ./:/srv/www/current:cached,ro

    php-fpm:
        build:
            dockerfile: docker/php-fpm/Dockerfile
            context: .
            args:
                build_env: prod
                GITLAB_HOST: "${GITLAB_HOST}"
                GITLAB_SECRET: "${GITLAB_SECRET}"
                GITLAB_USERNAME: "${GITLAB_USERNAME}"
        volumes:
          - ./images:/mnt/images
        restart: on-failure
        tmpfs:
            - /srv/www/current/images
            - /tmp
        command: sh -c 'cp -R /mnt/images/* /srv/www/current/images/ && php-fpm -R'
